# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b4b11d8806497b7162acdfb60e99a672457a7a3461a54d25f8711bb1b0906cf106f8e89cae7b17680a78c8626f2ceaf787de34ecabcd7c22014557b3bbdd12e

test:
  secret_key_base: 7f805f812d92bf40b2b4ee6e95b04525f674c4d113a0d3777153d20f2839dabcbe2df36aa57401031e0f8463deb29877206b69f02b59a0ce3f9dee457cd2b775

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
